config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :admins
    root to: 'main#index'

    resources :categories, except: :show
    resources :products do
      resources :prices, only: %i[edit update destroy] do
        get 'sell_form', on: :member
        patch 'sell', on: :member
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :nullify

  validates :title, presence: true, uniqueness: true, length: { maximum: 120 }
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :product

  validates :buy_price_cents, :sell_price_cents, numericality: { only_integer: true, greater_than: 0 }

  validates :quantity, presence: true, numericality: { only_integer: true },
                       inclusion: { in: :selling_quantiti, message: I18n.t('prices.quantity_inclusion') }

  scope :by_existing_prices, lambda { |buy_price, sell_price|
    where('buy_price_cents = ? AND sell_price_cents = ?', buy_price, sell_price)
  }

  monetize :buy_price_cents, :sell_price_cents, numericality: {
    greater_than: 0,
    less_than_or_equal_to: 300_000
  }

  def selling_quantiti
    (0..quantity)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many   :prices, dependent: :destroy
  belongs_to :category

  validates :name, presence: true

  accepts_nested_attributes_for :prices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  layout :choose_layout
  # before_action :authenticate_admin!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  protected

  def choose_layout
    admin_signed_in? ? 'account' : 'application'
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :category, only: %i[edit update destroy]

  def index
    @categories = Category.order(:title)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = t('.create_title', create_title: @category.title)
      redirect_to categories_path
    else
      flash.now[:warning] = t('.invalid_params')
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:success] = t('.successfully_update')
      redirect_to categories_path
    else
      flash.now[:warning] = t('.invalid_edit_params')
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
    flash[:danger] = t('.destroy_title', destroy_title: @category.title)
  end

  private

  def category_params
    params.require(:category).permit(:title, :description)
  end

  def category
    @category = Category.find(params[:id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  include PricesHelper
  before_action :product, :price

  def edit; end

  def update
    if @price.update(price_params)
      PriceUpdater.new(@product, @price).call
      flash[:success] = t('.successfully_update', update_product: @product.name)
      redirect_to products_path
    else
      flash.now[:warning] = t('.invalid_edit_params')
      render :edit
    end
  end

  def sell_form; end

  def sell
    if ProductPriceSeller.new(price_params, @price).call
      @price.destroy if @price.quantity.zero?
      flash[:success] = i18n_for_sold(price_params)
      redirect_to products_path
    else
      flash.now[:warning] = invalid_sell_flash_text(price_params)
      render :sell_form
    end
  end

  def destroy
    @price.destroy

    @product.destroy if @product.prices.empty?

    redirect_to products_path
    flash[:danger] = t('.destroy_name', destroy_name: @product.name)
  end

  private

  def price_params
    params.require(:price).permit(
      :product_id, :buy_price, :sell_price, :quantity
    )
  end

  def product
    @product = Product.find(params[:product_id])
  end

  def price
    @price = @product.prices.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductsHelper
  before_action :product, only: %i[edit update show destroy]
  before_action :new_product, :existing_product, :new_product_price, only: :create

  def index
    @products = Product.all
  end

  def show; end

  def new
    @product = Product.new
    @product.prices.build
  end

  def create
    case
    when ExistingProductPriceUpdater.new(@product, @existing_product, @product_price).update_quantity
      added_existing_prices_flash(@product_price.quantity, @existing_product.name)
    when ExistingProductPriceUpdater.new(@product, @existing_product, @product_price).update_prices
      added_new_prices_flash(@product_price.quantity, @product.name)
    when !@existing_product && @product.save
      added_new_product_flash(@product_price.quantity, @product.name)
    else
      invalid_new_params
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      flash[:success] = t('.successfully_update')
      redirect_to products_path
    else
      flash.now[:warning] = t('.invalid_edit_params')
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
    flash[:danger] = t('.destroy_product', destroy_product: @product.name)
  end

  private

  def product_params
    params.require(:product).permit(
      :name, :description, :category_id, prices_attributes: %i[id product_id buy_price sell_price quantity]
    )
  end

  def product
    @product = Product.find(params[:id])
  end

  def new_product
    @product = Product.new(product_params)
  end

  def existing_product
    @existing_product = Product.find_by(name: @product.name)
  end

  def new_product_price
    @product_price = @product.prices.try(:first)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/prices_helper.rb
module PricesHelper
  def invalid_params(price_params)
    price_params[:quantity].to_i > price.quantity || price_params[:quantity].to_i <= 0
  end

  def invalid_sell_flash_text(price_params)
    if price_params[:quantity].to_i < 1
      t('.quantity_must_be_higher')
    else
      t('.invalid_for_sell_params')
    end
  end

  def i18n_for_sold(price_params)
    t('.successfully_sold', quantity: price_params[:quantity], product: product.name)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def added_existing_prices_flash(quantity, name)
    flash[:success] = I18n.t('.existing_prices_success', quantity: quantity,
                                                         name: name,
                                                         item: i18n_item(quantity))
    redirect_to(products_path)
  end

  def invalid_new_params
    flash.now[:warning] = I18n.t('.invalid_new_params')
    render :new
  end

  def added_new_prices_flash(quantity, name)
    flash[:success] = I18n.t('.new_prices_success',
                             quantity: quantity,
                             item: i18n_item(quantity),
                             name: name)
    redirect_to products_path
  end

  def added_new_product_flash(quantity, name)
    flash[:success] = I18n.t('.new_product_success', quantity: quantity,
                                                     item: i18n_item(quantity),
                                                     name: name)
    redirect_to products_path
  end

  private

  def i18n_item(quantity)
    I18n.locale == :en ? I18n.t('.item').pluralize(quantity) : I18n.t('.item')
  end
end

app/views/categories/_category.html.slim
tr
  td
    span
      = category.title
  td
    span
      = category.description

  td.text-center.align-middle
    = link_to edit_category_path(category)
      h2.m-0
        = fa_icon 'edit', class: 'pt-1'
  td.text-center.align-middle
    = link_to category_path(category), method: :delete, data: { confirm: t('.confirmation') }
      h2
        = fa_icon 'trash'

app/views/categories/_form.html.slim
= simple_form_for [@category] do |f|

  .form-group
    = f.input :title, label: t('.title'), required: true, autofocus: true,
                     placeholder: t('.title_placeholder'),
                     input_html: { class: 'form-control' }
  .form-group
    = f.input :description, label: t('.description'),
                      placeholder: t('.description_placeholder'),
                      input_html: { class: 'form-control description-area' }

  .form-group.buttons
    = f.submit yield(:button), class: 'btn btn-primary me-4'
    = link_to  yield(:cancel_btn_text),
                          yield(:path),
                          class: 'btn btn-outline-danger'

app/views/categories/edit.html.slim
= provide(:button, t('.edit_button'))
= provide(:cancel_btn_text, t('.cancel'))
= provide(:path, categories_path)

.content.pt-4
  .form-component
    h1.text-center
      = t('.new_category')
    = render 'form', object: @category

app/views/categories/index.html.slim
.d-flex.justify-content-center
  h2.me-4
    = t('.all_categories')
  = link_to new_category_path
    button.btn.btn-outline-secondary
      = fa_icon 'plus'
table.table
  thead.thead
    tr
      th
        span
          = t('.header_title')
      th.text-center
        span
        = t('.header_description')
      th.text-center
        span
        = t('.header_edit')
      th.text-center
        span
        = t('.header_delete')
  tbody.tbody
    - @categories.each do |category|
      = render category

app/views/categories/new.html.slim
= provide(:button, t('.add_button'))
= provide(:cancel_btn_text, t('.cancel'))
= provide(:path, categories_path)
.container 
  .pt-4
    .form-component
      h1.text-center
        = t('.new_category')
      = render 'form', object: @category

app/views/layouts/account.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title
      = t('.site_title')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .m-top
      = render 'shared/account/header'
      = render 'shared/flash_msg'
      .container-fluid.mt-15 
        = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title
      = t('.site_title')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container-fluid.m-top
      = render 'shared/header'
      = render 'shared/flash_msg'
      .container-fluid.mt-15 
        = yield

app/views/main/index.html.slim
.d-flex.flex-column.justify-content-center.align-items-center
  h1.ms-4
    = t('.hello_world')
  p.pt-3
    = t('.it_is_trucco')
  = fa_icon 'camera-retro'

app/views/prices/_form.html.slim
= simple_form_for [@product, @price] do |f|
  .product_form
    .form-group.d-flex.justify-content-between.price
      = f.input :buy_price,   label: t('.buy_price_label'),
                                  required: true,
                                  placeholder: t('.buy_price_placeholder'),
                                  input_html: { class: 'form-control' }

      = f.input :sell_price,  label: t('.sell_price_label'),
                                  required: true,
                                  placeholder: t('.sell_price_placeholder'),
                                  input_html: { class: 'form-control' }
    .form-group.form-buttons.text-center.mt-2
      = f.submit t('.edit'), class: 'btn btn-primary me-4'
      = link_to  t('.cancel'), products_path, class: 'btn btn-outline-danger'

app/views/prices/edit.html.slim
.content.pt-4
  .form-component
    h1.text-center
      = t('.edit_price')
    p.text-center
      = t('.for')
      span.m-2
        = "#{@price.quantity} #{@product.name}"
    = render 'form', object: @price

app/views/prices/sell_form.slim
.content.pt-4
  .form-component
    h1.text-center
      = t('.sell_product')
    = simple_form_for [@product, @price], url: sell_product_price_path, method: :patch do |f|
      .product_selling_form
        .form-group.d-flex.justify-content-between.price
          = f.input :sell_price,  label: t('.sell_price_label'),
                                      required: true,
                                      placeholder: t('.sell_price_placeholder'),
                                      input_html: { class: 'form-control' }
        .form-group
          = f.input :quantity,    label: t('.quantity', quantity: @price.quantity),
                                      required: true,
                                      placeholder: t('.quantity_placeholder'),
                                      input_html: { class: 'form-control' }
        .form-group.form-buttons.text-center
          = f.submit t('.sell'), class: 'btn btn-primary me-2', data: { confirm: t('.confirmation') }
          = link_to  t('.cancel'), products_path, class: 'btn btn-outline-danger'

app/views/products/_form.html.slim
= simple_form_for @product do |f|
  .product_form
    .form-group
      = f.input :name, label: t('.name_label'), required: true, autofocus: true,
                      placeholder: t('.name_placeholder'),
                      input_html: { class: 'form-control' }
    .form-group
      = f.association :category, label: t('.category_label'),
                                prompt: t('.category'), input_html: { class: 'form-control' }
    .form-group
      = f.input :description, label: t('.description_label'),
                        placeholder: t('.description_placeholder'),
                        input_html: { class: 'form-control description-area' }
    = render 'products/prices', f: f unless request.env['PATH_INFO'] =~ /edit/

    .form-group.form-buttons.text-center
      = f.submit yield(:button), class: 'btn btn-primary me-4'
      = link_to  yield(:cancel_btn_text),
                            yield(:path),
                            class: 'btn btn-outline-danger'

app/views/products/_prices.html.slim
= f.simple_fields_for :prices do |price|
  .form-group.d-flex.justify-content-between.price
    = price.input :buy_price,   label: t('.buy_price_label'),
                                required: true,
                                placeholder: t('.buy_price_placeholder'),
                                input_html: { class: 'form-control' }

    = price.input :sell_price,  label: t('.sell_price_label'),
                                required: true,
                                placeholder: t('.sell_price_placeholder'),
                                input_html: { class: 'form-control' }
  .form-group
    = price.input :quantity,    label: t('.quantity'),
                                required: true,
                                placeholder: t('.quantity_placeholder'),
                                input_html: { class: 'form-control' }

app/views/products/_product.html.slim
- product.prices.each do |price|
  .row.item-line.justify-content-between.align-items-center.border-bottom.pt-3.pb-3
    .col-3.text-center
      = link_to product_path(product)
        = product.name
    .col-2.text-center
      = product&.category&.title
    .col-2.text-center
      = price.buy_price.format
    .col-2.text-center
      = price.sell_price.format 
    .col-1.text-center
      = price.quantity
    .col-1.text-center.align-middle
      = link_to sell_form_product_price_path(product, price)
        h3.m-0.sell-btn
          = fa_icon 'dollar'
    .col-1.text-center.align-middle
      .btn-more-hidden
        = link_to edit_product_price_path(product, price)
          h3.m-0
            = fa_icon 'edit'
        span.times
          = fa_icon 'times-circle'
        = link_to product_price_path(product, price), method: :delete, data: { confirm: t('.confirmation', quantity: price.quantity) }
          h3.m-0
            = fa_icon 'trash'
      #button-more.btn-more
        h3.m-0
          = fa_icon 'ellipsis-v'

app/views/products/_show_prices.html.slim
.prices-block.ps-3
  .row.border-bottom.border-dark.font-weight-bold
    .col-4.text-center
      = t('.product_name_header')
    .col-3.text-center
      = t('.buy_price')
    .col-3.text-center
      = t('.sell_price')
    .col-2.text-center
      = t('.quantity')
  - @product.prices.each do |price|
    .row.border-bottom.pt-3.pb-3
      .col-4.text-center
        = @product.name
      .col-3.text-center
        = price.buy_price.format
      .col-3.text-center
        = price.sell_price.format
      .col-2.text-center
        = "#{price.quantity} #{t('.pices')}"

app/views/products/edit.html.slim
= provide(:button, t('.edit_button'))
= provide(:cancel_btn_text, t('.cancel'))
= provide(:path, products_path)

.content.pt-4
  .form-component
    h1.text-center
      = t('.edit_product')
    = render 'form', object: @product

app/views/products/index.html.slim
.d-flex.justify-content-center
  h2
    = t('.all_products')

.container-fluid
  = link_to new_product_path
    button.btn.btn-outline-secondary
      = fa_icon 'plus'
  .row.justify-content-between.font-weight-bold.border-bottom.border-dark
    .col-3.text-center
      = t('.header_name')
    .col-2.text-center
      = t('.header_category')
    .col-2.text-center
      = t('.header_buy_price')
    .col-2.text-center
      = t('.header_sell_price')
    .col-1.text-center.p-0
      = t('.header_quantity')
    .col-1.text-center.p-0
      = t('.header_sell')
    .col-1.text-center.p-0
      = t('.header_more')
  .products_list
    = render @products

app/views/products/new.html.slim
= provide(:button, t('.add_button'))
= provide(:cancel_btn_text, t('.cancel'))
= provide(:path, products_path)

h1.m-4.text-center New Product

= render 'products/form', object: @product

app/views/shared/_flash_msg.html.slim
- flash.each do |type, msg|
    = content_tag(:div, msg, class: "alert alert-#{type}")

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
  = link_to t('.root_link_title'), root_path, class: 'navbar-brand ms-2'
  button.navbar-toggler aria-controls="navbarCollapse" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarCollapse" data-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  #navbarCollapse.collapse.navbar-collapse
    ul.navbar-nav.mx-auto
      li.nav-item.active
        a.nav-link href="#" 
          | Home
          span.sr-only (current)
      li.nav-item
        a.nav-link href="#"  Link
      li.nav-item
        a.nav-link.disabled href="#"  Disabled
    .d-flex.justify-content-end.m-2
      .dropdown.me-2
        button#dropdownMenuButton.btn.btn-transparent.auth-btn.dropdown-toggle aria-expanded='false' aria-haspopup='true' data-toggle='dropdown'
          = t('.select_lang')
        .dropdown-menu
          = link_to url_for(locale: :en), class: 'layout-dropdown-item dropdown-btn'
            = t('.btn_eng')
          = link_to url_for(locale: :uk), class: 'layout-dropdown-item dropdown-btn'
            = t('.btn_ukr')
      span.me-2
        = link_to t('.log_in'), new_admin_session_path, class: 'btn btn-outline-primary'

app/views/shared/account/_header.html.slim
nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
  = link_to t('.root_link_title'), root_path, class: 'navbar-brand ms-2'
  button.navbar-toggler aria-controls="navbarCollapse" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarCollapse" data-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  #navbarCollapse.collapse.navbar-collapse.justify-content-between
    ul.navbar-nav
      li.nav-item
        = link_to categories_path, class: 'nav-link'
          = t('.categories')
      li.nav-item
        = link_to products_path, class: 'nav-link'
          = t('.products')
      li.nav-item
        a.nav-link.disabled href="#"  Disabled
      li.nav-item.d-flex.justify-content-center.align-items-center.ms-2
        span.admin_greetings
          = t('.hello', hello: current_admin.full_name)
    form.form-inline.mt-2.mt-md-0.d-flex
      input.form-control.me-sm-2 aria-label="Search" placeholder="Search" type="text" /
      button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search
    .d-flex.justify-content-end.m-2
      .dropdown.me-2
        button#dropdownMenuButton.btn.btn-transparent.auth-btn.dropdown-toggle aria-expanded='false' aria-haspopup='true' data-toggle='dropdown'
          = t('.select_lang')
        .dropdown-menu
          = link_to url_for(locale: :en), class: 'layout-dropdown-item dropdown-btn'
            = t('.btn_eng')
          = link_to url_for(locale: :uk), class: 'layout-dropdown-item dropdown-btn'
            = t('.btn_ukr')
      = link_to t('.log_out'), destroy_admin_session_path, method: :delete, class: 'btn btn-outline-primary'